### ISSUE TITLE
gs.Map.Name is never assigned.

### ISSUE THREAD

**Issue by articblizz** [rakijah/CSGSI#2]
gs.Map.Name is always null because it's never assigned in the class.

**Comment by articblizz** [comment]
I downloaded the project, added
Name = GetString("name");
in the MapNode class and built it, works perfectly now! Thanks for doing this btw :)

**Comment by articblizz** [comment]
While I have your attention, is AllPlayers supposed to work in a normal game? If It's possible to do a scoreboard. As of right now, Allplayers is null.

**Comment by rakijah** [comment]
Thanks for bringing this to my attention, it will be fixed ASAP (as well as gs.Map.TeamCT and gs.Map.TeamT not being initialized).

The AllPlayers node is only sent by CSGO while either spectating a live match, watching through GOTV or watching a demo. This was presumably done because the node contains vital information about the enemy team such as HP etc.
