### ISSUE TITLE
Stats issue

### ISSUE THREAD

**Issue by bruxo00** [rakijah/CSGSI#5]
Hey. Well, I've been trying to make a program with your awesome library but I'm getting some weird problems, and I really don't know if it is CS:GO Game State Integration itself our your library that is messing things up.

The problem is: I'm in game and I die. I switch to someone's camera. If that person I'm spectating kills someone, dies, assists someone, it counts that ME killed someone, died, assisted, etc.

I don't know if you understand my problem, I hope so. Can you help me? :)

**Comment by rakijah** [comment]
The problem lies within the games implementation itself. The data sent within the `Player` tag is not just from the client that is running the game (as you would expect), but can for example contain information about the player you are spectating.

This means that you have to compare `Player.SteamID` to make sure you're currently tracking the intended player.
