### ISSUE TITLE
Enlarge the data arrival rate. Is that possible?

### ISSUE THREAD

**Issue by n1lsik** [rakijah/CSGSI#9]
Good afternoon. Is it possible to speed up the flow of information?
My config file:

```
"CSGSI Example"
{
    "uri" "http://localhost:3000"
    "timeout" "0.0"
    "buffer"  "0.0"
    "throttle" "0.1"
    "auth"
    {
        "token"             "CSGSI Test"
    }
    "data"
    {
        "provider"                  "1"
        "map"                       "1"
        "round"                     "1"
        "player_id"                 "1"
        "player_weapons"            "1"
        "player_match_stats"        "1"
        "player_state"              "1"
        "allplayers_id"             "1"
        "allplayers_state"          "1"
        "allplayers_match_stats"    "1"
    }
}
```

It gives an update rate of approximately once per second ... I'm working on it. But so far without success. Help, please.

**Comment by n1lsik** [comment]
Up

**Comment by rakijah** [comment]
Hey,
due to health related issues I can't really test this or help you with this problem at the moment. Sorry.

**Comment by n1lsik** [comment]
Ok, I'll wait. I hope you'll get better soon!

**Comment by n1lsik** [comment]
What happened to you? I get scared...

**Comment by rage311** [comment]
I just started using this library and Valve's GSI, so I don't know whether Valve's GSI used to be different or not, but the update rate from the game itself is slow and inconsistent.  The game seems to update at random intervals, even potentially delaying or missing important "events" like: kills/deaths, observed player weapon switching, ammo decrease, etc.  I know this isn't the fault of this library (CSGSI) because I've monitored the network traffic to watch when the updates actually come from the game itself.  The only way I've found to improve it is to put a fast heartbeat setting in your gamestate_integration_*.cfg file, eg `"heartbeat" "0.1"`.  I think 0.1 is the fastest setting for heartbeat, based on my testing.  Hopefully that helps you.

I REALLY hope Valve improves their end, because having to rely on a full update via heartbeat in order to get (almost) enough information is a poor solution.  Even trying to do something as simple as a kill feed is really difficult since the information about who killed and who was killed is frequently split between 2 updates...  I think they need to provide event data in addition to the overall game state data, so that instead of:
`if (gs.Player.State.Health == 0 && gs.Previously.Player.State.Health > 0) { ... }`
you could just listen for a "player death" event.  I doubt they will improve their end much though, so this is just a pipe dream.

**Comment by n1lsik** [comment]
Thanks. It really speeds up the process!
